matrix:
  include:
    - os: linux
      language: node_js
      node_js: 8.9.3
      dist: trusty
      sudo: required
    - os: windows
      language: node_js
      node_js: 8.9.3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    fi

install:
  - yarn install --network-timeout 1000000 # Timeout needed for Windows (really slow)

script:
  - yarn test
  - yarn e2e
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn checkformat --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
  - yarn checkcommit

addons:
  chrome: stable

cache:
  directories:
    - node_modules

notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true
