[package]
name = "daemon-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.0", features = ["sync", "macros", "io-util", "rt", "time"] }
interprocess = { version = "2.2.3", features = ["tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
napi = { version = "2.16.0", default-features = false, features = [
    "anyhow",
    "napi4",
    "tokio_rt",
    "async",
    "chrono_date",
] }
napi-derive = "2.16.0"
anyhow = "1.0.71"
thiserror = "1.0.40"
parking_lot = { version = "0.12.1", features = ["send_guard"] }
dashmap = { version = "5.5.3", features = ["rayon"] }
crossbeam-channel = "0.5"
tracing = "0.1.37"
tokio-retry = "0.3"
bincode = "1.3"
async-trait = "0.1"
futures = "0.3.28"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.13"

[build-dependencies]
napi-build = "2.1.3"

[lib]
crate-type = ['cdylib']
