[build]
target-dir = 'build/target'

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C",
    "target-feature=-crt-static",
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]