[package]
name = 'nx'
version = '0.1.0'
edition = '2024'

[profile.release-wasi]
codegen-units = 16
debug = 'full'
inherits = "release"
lto = "thin"
opt-level = "z"
strip = "none"

[dependencies]
tokio = { version = "1.44.0", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
] }
anyhow = "1.0.71"
better-panic = "0.3.0"
colored = "2"
color-eyre = "0.6.3"
crossbeam-channel = '0.5'
dashmap = { version = "5.5.3", features = ["rayon"] }
dunce = "1"
flate2 = "1.1.1"
fs_extra = "1.3.0"
futures = "0.3.28"
globset = "0.4.10"
hashbrown = { version = "0.14.5", features = ["rayon", "rkyv"] }
ignore = '0.4'
itertools = "0.10.5"
once_cell = "1.18.0"
parking_lot = { version = "0.12.1", features = ["send_guard"] }
napi = { version = "2.16.0", default-features = false, features = [
    "anyhow",
    "napi4",
    "tokio_rt",
    "async",
    "chrono_date",
] }
napi-derive = '2.16.0'
nom = '7.1.3'
regex = "1.9.1"
rayon = "1.7.0"
rkyv = { version = "0.7", features = ["validation"] }
swc_common = "0.31.16"
swc_ecma_parser = { version = "0.137.1", features = ["typescript"] }
swc_ecma_visit = "0.93.0"
swc_ecma_ast = "0.107.0"
sysinfo = "0.33.1"
rand = "0.9.0"
tar = "0.4.44"
terminal-colorsaurus = "0.4.0"
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tokio-util = "0.7.9"
tracing-appender = "0.2"
tui-logger = { version = "0.17.2", features = ["tracing-support"] }
tui-term = { git = "https://github.com/JamesHenry/tui-term", rev = "88e3b61425c97220c528ef76c188df10032a75dd" }
walkdir = '2.3.3'
xxhash-rust = { version = '0.8.5', features = ['xxh3', 'xxh64'] }
vt100-ctt = { git = "https://github.com/JamesHenry/vt100-rust", rev = "b15dc3b0f7db94167a9c584f1d403899c0cc871d" }
serde = "1.0.219"
serde_json = "1.0.140"

sha2 = "0.10.8"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "psapi", "shellapi"] }

[target.'cfg(all(not(windows), not(target_family = "wasm")))'.dependencies]
mio = "1.0"
nix = { version = "0.30.0", features = ["process", "signal"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.4.1"
crossterm = { version = "0.29.0", features = ["event-stream", "use-dev-tty"] }
portable-pty = { git = "https://github.com/cammisuli/wezterm", rev = "b538ee29e1e89eeb4832fb35ae095564dce34c29" }
ignore-files = "2.1.0"
fs4 = "0.12.0"
ratatui = { version = "0.29", features = ["scrolling-regions"] }
reqwest = { version = "0.12.15", default-features = false, features = [
    "rustls-tls",
] }
rusqlite = { version = "0.32.1", features = ["bundled", "array", "vtab"] }
watchexec = "3.0.1"
watchexec-events = "2.0.1"
watchexec-filterer-ignore = "3.0.0"
watchexec-signals = "2.1.0"
machine-uid = "0.5.2"
interprocess = { version = "2.2.3", features = ["tokio"] }
jsonrpsee = { version = "0.25.1", features = [
    "client-core",
    "async-client",
    "macros",
    "http-client",
] }

[lib]
crate-type = ['cdylib']

[build-dependencies]
napi-build = '2.1.3'

[dev-dependencies]
assert_fs = "1.0.10"
insta = "1.42.2"
# This is only used for unit tests
swc_ecma_dep_graph = "0.109.1"
tempfile = "3.13.0"
uuid = { version = "1.0", features = ["v4"] }
