name: Generate embeddings

on:
  schedule:
    - cron: "0 5 * * 0,4" # sunday, thursday 5AM

jobs:
  cache-and-install:
    if: github.repository == 'nrwl/nx'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.19.0']

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20.19.0'
          package-manager-cache: false

      - name: Install pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
        id: pnpm-install
        with:
          version: 10.11.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build docs
        run: npx nx build astro-docs

      - name: Run embeddings script
        run: node --import tsx tools/documentation/create-embeddings/src/main.mts --mode=astro
        env:
            NX_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NX_NEXT_PUBLIC_SUPABASE_URL }}
            NX_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NX_SUPABASE_SERVICE_ROLE_KEY }}
            NX_OPENAI_KEY: ${{ secrets.NX_OPENAI_KEY }}
